name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud credentials
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > $HOME/gcloud-service-key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

      - name: Set Google Cloud project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Google Cloud
        run: |
          gcloud app deploy --quiet
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-service-key.json
